

CREATE PROCEDURE `UPDATE_BITACORA` (`ID_SUC` INT, `ID_USU` VARCHAR(25),`OPE` VARCHAR(150),
   `D_OPERACION` VARCHAR (45),`IP` VARCHAR(45))
    INSERT INTO BITACORA VALUES (NULL,ID_SUC, ID_USU,OPE,D_OPERACION,NOW(),IP, TRUE);
    

CREATE PROCEDURE `UPDATE_CLIENTE` (`PREV_NIT` VARCHAR(15),`NIT_CLIENTE` VARCHAR(15),`NC_IN` VARCHAR(45),
`AC_IN` VARCHAR(45),`DIR`VARCHAR(128),`TC_IN` VARCHAR(15),`TEC_IN` VARCHAR(15), `DIAS` INT, `LIMITE` FLOAT,
 `DISPONIBLE` FLOAT) 
  UPDATE CLIENTE SET ESTADO_TUPLA = TRUE,
  ID_CLIENTE = NIT_CLIENTE,
  NOMBRE_CLIENTE = NC_IN,
  APELLIDO_CLIENTE = AC_IN,
  TELEFONO_CLIENTE = TEC_IN,
  DIRECCION_CLIENTE = DIR,
  ID_TIPO_CLIENTE = (SELECT ID_TIPO_CLIENTE FROM TIPO_CLIENTE WHERE TIPO = TC_IN LIMIT 1),
  LIMITE_CREDITO = LIMITE,
  CREDITO_DISPONIBLE = DISPONIBLE,
  DIAS_CREDITO = DIAS
  WHERE ID_CLIENTE = PREV_NIT;
  
  
  CREATE PROCEDURE `INGRESO_CLIENTE` (`ID_CLIENTE` VARCHAR(15), `NOMBRE_CLIENTE` VARCHAR(45),`APELLIDO_CLIENTE` VARCHAR(45),
`DIRECCION` VARCHAR(128),`TELEFONO_CLIENTE` VARCHAR(15),`LIMITE` FLOAT,`DIAS` INT,`TIPO_C` VARCHAR(45)) 
 INSERT INTO CLIENTE VALUES (ID_CLIENTE,(SELECT ID_TIPO_CLIENTE FROM TIPO_CLIENTE WHERE TIPO = TIPO_C LIMIT 1),
 NOMBRE_CLIENTE,APELLIDO_CLIENTE,DIRECCION,TELEFONO_CLIENTE,LIMITE,LIMITE,DIAS,NOW(),TRUE);
 
 
CREATE PROCEDURE `INGRESO_PROVEEDOR` (`ID_PROVEEDOR` VARCHAR(45) ,`NOMBRE_PROVEEDOR` VARCHAR(225),
`EMAIL_PROVEEDOR` VARCHAR(155),`DIR_PROVEEDOR` VARCHAR(45),`TELEFONO_PROVEEDOR` VARCHAR(45)) 
 INSERT INTO PROVEEDOR VALUES (ID_PROVEEDOR,NOMBRE_PROVEEDOR,EMAIL_PROVEEDOR,DIR_PROVEEDOR,TELEFONO_PROVEEDOR,NOW(),TRUE);
 
 
 CREATE PROCEDURE `UPDATE_PROVEEDOR` (`ID_PD` VARCHAR(45),`ID_PROVEEDORN` VARCHAR(45) ,
`NM_PROVEEDOR` VARCHAR(225),`EM_PROVEEDOR` VARCHAR(150),`DIR_PROVEEDOR` VARCHAR(155),`TEL_PROVEEDOR` VARCHAR(45)) 
  UPDATE PROVEEDOR SET ESTADO_TUPLA = TRUE,
  ID_PROVEEDOR = ID_PROVEEDORN,
  NOMBRE_PROVEEDOR = NM_PROVEEDOR,
  EMAIL_PROVEEDOR = EM_PROVEEDOR,
  DIRECCION_PROVEEDOR = DIR_PROVEEDOR,
  TELEFONO_PROVEEDOR = TEL_PROVEEDOR
  WHERE ID_PROVEEDOR = ID_PD;
  
   CREATE PROCEDURE `CIERRA_COMPRA` (`ID_C` INT,`SUBTOTAL` FLOAT, `DESCUENTOS` FLOAT, `TOTAL` FLOAT)
     UPDATE COMPRA SET 
     SUBTOTAL_COMPRA = SUBTOTAL,
     DESCUENTO  = DESCUENTOS,
     TOTAL_FINAL = TOTAL
     WHERE ID_COMPRA = ID_C;
     
     -- ACTUALIZA LA CUENTA DEL PROVEEDOR
     CREATE PROCEDURE `ACTUALIZA_CUENTA_PROVEEDOR` (`ABONO` FLOAT , `CUENTA` VARCHAR(45))
 UPDATE CUENTA_POR_PAGAR SET TOTAL_PAGADO = TOTAL_PAGADO + ABONO WHERE ID_CUENTA_POR_PAGAR = CUENTA;
 
 
 CREATE PROCEDURE `NUEVO_TRASLADO_MATERIA` (`COD_TRASLADO` INT, `USUARIO` VARCHAR(45), `TRASLADO` VARCHAR(45), `DESTINO` VARCHAR(45))
   INSERT INTO TRASLADOS VALUES (COD_TRASLADO, USUARIO, (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = TRASLADO LIMIT 1),
   (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = DESTINO LIMIT 1),NOW(),TRUE, TRUE);
 
 CREATE PROCEDURE `INGRESA_PRODUCTOS_TRASLADO_MATERIA` (`COD_TRASLADO` INT, `ID_MATERIA` VARCHAR(45), 
 `CANTIDAD` FLOAT )
  INSERT INTO MATERIA_TRASLADO VALUES (NULL, COD_TRASLADO, ID_MATERIA, CANTIDAD, TRUE);
  -- DROP PROCEDURE INGRESA_PRODUCTOS_TRASLADO_MATERIA;
  
  CREATE PROCEDURE `ACTUALIZA_GASTO` (`GASTO` INT, `SUCURSAL` VARCHAR(45),`NDESC` VARCHAR(200), 
`FECHA` DATE, `NOBSERV` VARCHAR(200), `NMONTO` FLOAT)
 UPDATE GASTOS SET 
  ID_SUCURSAL = (SELECT ID_SUCURSAL FROM SUCURSAL WHERE NOMBRE_SUCURSAL = SUCURSAL LIMIT 1),
  DESCRIPCION = NDESC,
  FECHA_GASTO = FECHA,
  OBSERVACIONES = NOBSERV,
  MONTO = NMONTO
  WHERE IDGASTO = GASTO;
  
  
    CREATE PROCEDURE `ACTUALIZA_PRESENTACION` (`STOCK` VARCHAR(45), `CODIGO` VARCHAR(45),`DESCR` VARCHAR(120), 
`CANTIDAD` FLOAT, `CANTIDAD_M` FLOAT,`PC` FLOAT, `P1` FLOAT,`P2` FLOAT,`P3` FLOAT,`P4` FLOAT,`P5` FLOAT)
 UPDATE mercaderia_presentaciones SET 
  DESCRIPCION = DESCR,
  CANTIDAD_POR_PRESENTACION = CANTIDAD,
  CANTIDAD_MINIMA = CANTIDAD_M,
  PRECIO_COSTO = PC,
  PRECIO_1 = P1,
  PRECIO_2 = P2,
  PRECIO_3 = P3,
  PRECIO_4 = P4,
  PRECIO_5 = P5
  WHERE ID_STOCK = STOCK AND ID_MERCADERIA = CODIGO;
  
  

  